### ISSUE TITLE
rdflib-jsonld package not found Suggestion: Edit readme solve env instructions 

### ISSUE THREAD

**Issue by Leandroscholz** [NeuBIAS/bise-core-ontology#11]
Hi, I think there should be an update in the instructions to solve de anaconda environment. I have got the following message after runing ``` conda install flask rdflib rdflib-jsonld pymongo -c conda-forge ```
```
PackagesNotFoundError: The following packages are not available from current channels:

  - rdflib-jsonld
```
I managed to get the module by running 
```
pip install rdflib-jsonld
```
In case necessary i am running Ubuntu 19.04 and conda 4.5.4 

Regards,

**Comment by albangaignard** [comment]
Yes indeed, rdflib-jsonld is available from the bioconda channel. Thanks again for reporting ! 
I updated the documentation : 
```
conda install flask rdflib pymongo -c conda-forge
conda install rdflib-jsonld -c bioconda
```
